version: '3.7'

services:

  my-app:
    container_name: frontend_visitcontrol
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/frontend'
      - '/frontend/node_modules'
    ports:
      - '8081:8080'